### ISSUE TITLE
Import pass from PDF

### ISSUE THREAD

**Issue by ligi** [ligi/PassAndroid#81]
Don't really like this - but seems to be needed - but there should be a big warning that this is discouraged as we will have no maschine-readable data for this pass

**Comment by ligi** [comment]
Will use https://developer.android.com/reference/android/graphics/pdf/PdfRenderer.html for this. This has the disadvantage of being API21+ but other possibilities would bring heavy dependencies

**Comment by wmertens** [comment]
can't you scan any barcodes in the pdf and reproduce them cleanly? For common types, like boarding passes, you could extract data as well.

Then any image can be used as a source.

**Comment by ligi** [comment]
how would you extract data for common types?

**Comment by martinruenz** [comment]
I don't want to open a new issue for this, but the current behaviour has drawbacks. If a barcode is small in the PDF the conversion might loose enough quality, so that the code is not readable any longer. I think storing the original PDF would make more sense.
Also, I like @wmertens's idea. Maybe something like pdfbox could help, see http://stackoverflow.com/questions/18098400/how-to-get-raw-text-from-pdf-file-using-java for instance.
